// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: proto.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LiveChat_GetLiveChatData_FullMethodName = "/proto.LiveChat/GetLiveChatData"
)

// LiveChatClient is the client API for LiveChat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiveChatClient interface {
	GetLiveChatData(ctx context.Context, in *LiveChatData, opts ...grpc.CallOption) (*LiveChatData, error)
}

type liveChatClient struct {
	cc grpc.ClientConnInterface
}

func NewLiveChatClient(cc grpc.ClientConnInterface) LiveChatClient {
	return &liveChatClient{cc}
}

func (c *liveChatClient) GetLiveChatData(ctx context.Context, in *LiveChatData, opts ...grpc.CallOption) (*LiveChatData, error) {
	out := new(LiveChatData)
	err := c.cc.Invoke(ctx, LiveChat_GetLiveChatData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiveChatServer is the server API for LiveChat service.
// All implementations must embed UnimplementedLiveChatServer
// for forward compatibility
type LiveChatServer interface {
	GetLiveChatData(context.Context, *LiveChatData) (*LiveChatData, error)
	mustEmbedUnimplementedLiveChatServer()
}

// UnimplementedLiveChatServer must be embedded to have forward compatible implementations.
type UnimplementedLiveChatServer struct {
}

func (UnimplementedLiveChatServer) GetLiveChatData(context.Context, *LiveChatData) (*LiveChatData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLiveChatData not implemented")
}
func (UnimplementedLiveChatServer) mustEmbedUnimplementedLiveChatServer() {}

// UnsafeLiveChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiveChatServer will
// result in compilation errors.
type UnsafeLiveChatServer interface {
	mustEmbedUnimplementedLiveChatServer()
}

func RegisterLiveChatServer(s grpc.ServiceRegistrar, srv LiveChatServer) {
	s.RegisterService(&LiveChat_ServiceDesc, srv)
}

func _LiveChat_GetLiveChatData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LiveChatData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiveChatServer).GetLiveChatData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LiveChat_GetLiveChatData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiveChatServer).GetLiveChatData(ctx, req.(*LiveChatData))
	}
	return interceptor(ctx, in, info, handler)
}

// LiveChat_ServiceDesc is the grpc.ServiceDesc for LiveChat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiveChat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LiveChat",
	HandlerType: (*LiveChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLiveChatData",
			Handler:    _LiveChat_GetLiveChatData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
